feat: 상품 수정 controller 구현
woowasap/ASAP pull request #42
Opened 2023-08-05 04:15 UTC by pushedrumex

## 🚀 어떤 기능을 개발했나요?
상품 수정 controller를 구현하였습니다.

## 🕶️ 어떻게 해결했나요?
- [x] PUT /v1/products/{product-id} 에 매핑되는 controller 작성

## 🦀 이슈 넘버
- resolve #27

2023-08-05 04:26 UTC, grolarkim requested changes

2023-08-05 04:26 UTC, grolarkim commented on shop/shop-service/src/main/java/shop/woowasap/shop/service/dto/UpdateProductRequest.java
> +package shop.woowasap.shop.service.dto;
패키지 이동 과정에서 이전에 참조하던 곳이 있어서 컴파일에러가 났습니다. 수정해주세요.

2023-08-08 11:16 UTC, ProtoSeo requested changes

2023-08-08 11:16 UTC, ProtoSeo commented on shop/shop-domain/src/main/java/shop/woowasap/shop/dto/UpdateProductRequest.java
dto가 domain에 있는게 조금 어색한 것 같아요! service 계층에 있으면, `shop-controller/build.gradle` 에서 `domain`의 의존성을 가져오지 않고 해결할 수 있을 것 같아요!

2023-08-08 11:16 UTC, ProtoSeo commented on shop/shop-domain/src/main/java/shop/woowasap/shop/dto/UpdateProductRequest.java
`package` 구문과 `import` 구문이 붙어 있는것 처럼 보이는데 확인 해주시면 좋을 것 같아요~

2023-08-08 11:16 UTC, ProtoSeo commented on shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductController.java
> +    public ResponseEntity<Void> updateProduct(@PathVariable("product-id") Long productId, UpdateProductRequest request) {
NIL: 이건 그냥 궁금한 건데, `product-id` 로 작성하신 이유가 있는지 궁금해요! 아래와 같이 작성할 수도 있을 것 같아서 궁금해졌어요!

```suggestion
    @PutMapping("/{productId}")
    public ResponseEntity<Void> updateProduct(@PathVariable Long productId, UpdateProductRequest request) {
```

2023-08-08 11:30 UTC, pushedrumex commented on shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductController.java
> +    public ResponseEntity<Void> updateProduct(@PathVariable("product-id") Long productId, UpdateProductRequest request) {
저희 노션에 있는 API 명세대로 작성했습니다!

2023-08-08 11:39 UTC, pushedrumex commented on shop/shop-domain/src/main/java/shop/woowasap/shop/dto/UpdateProductRequest.java
아까 domain에 두자는 얘기를 해서, service에서 domain으로 이동하는거로 헷갈렸습니다 😅바로 수정하겠습니다!🚀

2023-08-08 12:57 UTC, ProtoSeo approved these changes

2023-08-08 14:29 UTC, devxb approved these changes

2023-08-08 14:29 UTC, devxb commented on coverage-exclude.asap
> +exclude shop/woowasap/shop/controller/*
```suggestion
exclude shop/woowasap/shop/controller/*

```

2023-08-08 14:29 UTC, devxb commented on shop/shop-domain/src/test/java/shop/woowasap/domain/support/ProductValidator.java
> +        LocalDateTime endTime,
**NIT**

이거 그냥 Product로 받으면 안되나용??
이러면 재사용하기 좀 힘들거 같아요

2023-08-09 01:05 UTC, grolarkim approved these changes

2023-08-09 01:05 UTC, merged