feat: 회원 가입 컨트롤러
woowasap/ASAP pull request #87
Opened 2023-08-11 09:25 UTC by grolarkim

## 🚀 어떤 기능을 개발했나요?
회원가입을 위한 컨트롤러를 개발하였습니다. 또한 여기에 사용되는 스프링 시큐리티를 위한 infra 모듈이 추가되었습니다.

## 🕶️ 어떻게 해결했나요?
- [x] 유저 컨트롤러 추가 
- [x] 회원가입 메소드 추가 
- [x] 예외 핸들러 추가
- [x] infra 모듈 추가
- [x] Spring Security 추가
- [x] 웹 설정에 전체 허용 -> 로그인 기능과 함께 수정해야함
- [x] validate를 위한 컨트롤러 용 dto 생성

## 🦀 이슈 넘버
- resolve #25

2023-08-11 11:29 UTC, ProtoSeo commented on app/src/test/java/shop/woowasap/accept/AuthAcceptanceTest.java
테스트에서 사용하는 변수들 `final` 키워드 붙여주시면 좋을 것 같아요!

2023-08-11 11:29 UTC, ProtoSeo commented on infra/src/main/java/shop/woowasap/infra/filter/JwtTokenProvider.java
> +    public String createAccessToken(UserResponse userResponse) {
`UserResponse`에도 `final` 키워드 붙여주시면 좋을 것 같아요!

2023-08-11 13:02 UTC, devxb requested changes
수고하셨습니다~

2023-08-11 13:02 UTC, devxb commented on infra/src/main/java/shop/woowasap/infra/configuration/WebSecurityConfiguration.java
> +    CorsConfigurationSource corsConfigurationSource() {
**NIT**

저희 리뷰어님은 package-private 으로 접근제어자를 두어도 되는 상황에도 package-private 접근제어자는 사용하지 않고, 그냥 `public`, `price`, `protected` 로 명시해준다고 하시더라구요

2023-08-11 13:02 UTC, devxb commented on infra/src/main/java/shop/woowasap/infra/configuration/WebSecurityConfiguration.java
> +    CorsConfigurationSource corsConfigurationSource() {
Cors에 대한 정책은 app 모듈에서 세팅하는게 더 좋아보이네요!

2023-08-14 07:45 UTC, devxb approved these changes
🚀

2023-08-14 07:46 UTC, merged